language: android
jdk: oraclejdk7
env:
  matrix:
    - ANDROID_TARGET=android-23  ANDROID_ABI=armeabi-v7a
  global:
    - COVERALLS_REPO_TOKEN=gMnsR0XfIpFzW5H13OJGqbxns9L1rBnB1
sudo: false

# Android config
android:
  components:
    - platform-tools
    - build-tools-21.1.2
    - android-23
    - extra-android-support
    - extra-android-m2repository
  licenses:
    - '.+'

# Only send email on failure.
notifications:
  email:
    recipients:
      - wijnand@ledge.us
    on_success: never
    on_failure: always

# Set up.
before_install:
  # Dependencies
  - git clone git@github.com:itabulous/ledgecommon_android.git ~/build/itabulous/ledgecommon_android/
  - git clone git@github.com:itabulous/ledgelinkapi_android.git ~/build/itabulous/ledgelinkapi_android/
  # Create gradle.properties files.
  - echo "HOME=$HOME" > ~/build/itabulous/ledgecommon_android/gradle.properties
  - echo "HOME=$HOME" > ~/build/itabulous/ledgelinkapi_android/gradle.properties
  - echo "HOME=$HOME" > ~/build/itabulous/ledgelinksdk_android/gradle.properties

install:
  # Add dependencies to local m2 repo.
  - cd ~/build/itabulous/ledgecommon_android
  - gradle install
  - cd ~/build/itabulous/ledgelinkapi_android
  - gradle --configure-on-demand -p api install
  - gradle -p wrappers/wrapper-retrofit2 install
  - cd ~/build/itabulous/ledgelinksdk_android
  - gradle --configure-on-demand -p sdk install

# Running tests.
script:
  - gradle -p ui testDebugUnitTestCoverage

after_success:
  # Copy file to expected location.
  - mkdir -p ~/build/itabulous/ledgelinksdk_android/ui/build/reports/jacoco/test
  - cp ~/build/itabulous/ledgelinksdk_android/ui/build/reports/jacoco/testDebugUnitTestCoverage/testDebugUnitTestCoverage.xml ~/build/itabulous/ledgelinksdk_android/ui/build/reports/jacoco/test/jacocoTestReport.xml
  # Send coverage info to Coveralls.io.
  - gradle -p ui coveralls
