language: android
jdk: oraclejdk8
env:
  matrix:
    - ANDROID_TARGET=android-23  ANDROID_ABI=armeabi-v7a
sudo: false

# Android config
android:
  components:
    - platform-tools
    - build-tools-23.0.0
    - android-23
    - android-24
    - extra-android-support
    - extra-android-m2repository
  licenses:
    - '.+'

# Send notifications on Android Slack channel.
notifications:
  email: false
  slack:
    rooms:
      secure: "AdW02OHYc6Vjuf1PCc+pJVTStqxFU8hJCsdOfCIy8lqod3df/BQpVvy1biKyjFhFa7GySWvkuGdTW9eAF8j7q/OvXF4I7Gqejqi2nXszXqOQQc7gSLFsmwLxBTiPOrqc2WNeV2OPIzOxZpTZVI8D7TlP/7NdzA3QFTXyJlOnhC6jMflqliMqxMNRWEwFRj3HIPFdLpE8ABysnWsN4JV2TZvRVcQHlnI05y56vivZuGS1qUidIaoCAaX0okdN/jDdifVREFxXdjYk1Iy3oAZLgOednSwvRrUohQabJ9w98PIOKmko1khBGSe6iRYYmCtTariZM1uMqNL9mUv0RZ2dYBkY+NcAMcZ0dS4yODKjcqyGOIoXGIR97EogfJ/83ossgqS30r15bb8UcoNQwVmBuNk09MBWwblCJ8ICvOPZmharwdMFt6a9FDYPFDOz7rgA+cdIGSlGLsYgtf5tdh0/w3CGF0idP1C/Z6Lgl3jP2nK0rPXxN5FLxNHDcjetS82of/YlNR2yEj+FDMciyBj0U27wTcJnGtsWnv7zoriMwtWjUnpJMDNWHJ5VIF57dLawkQb4lKEDcWktzO7HdtbNAYSk6BEkZp7bMaDYx4WNpnfegLw4OM2NZztyZv77KGtsSg0+N+MFh53gEuwxdx68UPIrV2nU5RRspWgwSxG5zZM="

# Set up.
before_install:
  # Dependencies
  - git clone git@github.com:itabulous/ledgecommon_android.git ~/build/itabulous/ledgecommon_android/
  # Create gradle.properties files.
  - echo "HOME=$HOME" > ~/build/itabulous/ledgecommon_android/gradle.properties
  - echo "HOME=$HOME" > ~/build/itabulous/sdk_android/gradle.properties

install:
  # Add dependencies to local m2 repo.
  - cd ~/build/itabulous/ledgecommon_android
  - chmod +x gradlew
  - ./gradlew install
  - cd ~/build/itabulous/sdk_android
  - chmod +x gradlew
  - ./gradlew --configure-on-demand -p sdk install

# Running tests.
script:
  - ./gradlew --configure-on-demand -p sdk testDebugUnitTestCoverage
  - cd ~/build/itabulous/sdk_android/shift-sdk
  - ../gradlew --configure-on-demand assembleDebug testDebugUnitTestCoverage

after_success:
  # Copy file to expected location.
  - mkdir -p ~/build/itabulous/sdk_android/sdk/build/reports/jacoco/test
  - cp ~/build/itabulous/sdk_android/sdk/build/reports/jacoco/testDebugUnitTestCoverage/testDebugUnitTestCoverage.xml ~/build/itabulous/sdk_android/sdk/build/reports/jacoco/test/jacocoTestReport.xml
  - mkdir -p ~/build/itabulous/sdk_android/shift-sdk/build/reports/jacoco/test
  - cp ~/build/itabulous/sdk_android/shift-sdk/build/reports/jacoco/testDebugUnitTestCoverage/testDebugUnitTestCoverage.xml ~/build/itabulous/sdk_android/shift-sdk/build/reports/jacoco/test/jacocoTestReport.xml
  # Send coverage info to Codecov.io.
  - bash <(curl -s https://codecov.io/bash) -t e3fe9fad-cf90-4b4c-94b8-ecdf33c73105
